name:                knapla
version:             0.1.0.0
github:              "drozdziak1/knapla"
license:             BSD3
author:              "Stan Drozd"
maintainer:          "drozdziak1@gmail.com"
copyright:           "2021 Stan Drozd"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/knapla#readme>

dependencies:
- base >= 4.7 && < 5
- GLUT

library:
  source-dirs: src

executables:
  knapla-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - knapla

tests:
  knapla-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - knapla
